# Generated by Django 4.2.30 on 2026-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ecc_encrypted_private_key",
            field=models.TextField(
                blank=True, help_text="Password-encrypted ECC private key", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ecc_public_key",
            field=models.TextField(
                blank=True, help_text="ECC public key (point) in JSON", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="encrypted_private_key",
            field=models.TextField(
                blank=True, help_text="Password-encrypted RSA private key", null=True
            ),
        ),
    ]
