# Generated by Django 4.2.30 on 2026-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_ecc_encrypted_private_key_user_ecc_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_backup_codes",
            field=models.TextField(
                blank=True, help_text="Backup codes for 2FA", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable two-factor authentication"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, help_text="TOTP secret key", max_length=32, null=True
            ),
        ),
    ]
