# Generated by Django 4.2.30 on 2026-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_two_factor_backup_codes_user_two_factor_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="User verified by Central Authority"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Account active status (Admin can suspend)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("authority", "Central Authority"),
                ],
                default="user",
                max_length=15,
            ),
        ),
    ]
