# Generated by Django 4.2.30 on 2026-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_balance_user_is_verified_user_kyc_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_info",
            field=models.TextField(
                blank=True, help_text="User contact info (phone/address)", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_info_encrypted",
            field=models.TextField(
                blank=True, help_text="RSA encrypted contact info", null=True
            ),
        ),
    ]
