# Generated by Django 4.2.30 on 2026-07-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_card_number_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_frozen',
            field=models.BooleanField(default=False, help_text='User self-frozen transactions'),
        ),
    ]
