# Generated by Django 4.2.30 on 2026-04-25 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always visible)",
                        max_digits=20,
                    ),
                ),
                (
                    "encrypted_payload",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted transaction data based on privacy level",
                        null=True,
                    ),
                ),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("private_metadata", "Private Metadata"),
                            ("high_privacy", "High Privacy"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "hmac_signature",
                    models.CharField(
                        help_text="HMAC signature for transaction integrity",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_encrypted", models.TextField(blank=True, null=True)),
                ("notes_encrypted", models.TextField(blank=True, null=True)),
                ("category_encrypted", models.TextField(blank=True, null=True)),
                (
                    "category_visible",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Metadata",
                "verbose_name_plural": "Transaction Metadata",
                "db_table": "transaction_metadata",
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger",
                "verbose_name_plural": "Ledgers",
                "db_table": "ledgers",
            },
        ),
    ]
