# Generated by Django 4.2.30 on 2026-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="content_encrypted",),
        migrations.RemoveField(model_name="post", name="title_encrypted",),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(
                default="Migrated Post Content", help_text="Post content"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(
                default="Migrated Post Title", help_text="Post title", max_length=255
            ),
        ),
    ]
