# Generated by Django 4.2.30 on 2026-07-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerIntegrityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('secure', 'Secure'), ('tampered', 'Tampered')], default='secure', max_length=10)),
                ('verified_count', models.IntegerField(default=0)),
                ('tampered_details', models.JSONField(blank=True, default=list, help_text='Array of {transaction_id, expected_hash, actual_hash}')),
            ],
            options={
                'db_table': 'ledger_integrity_reports',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='pass', max_length=10)),
                ('passed_tests_count', models.IntegerField(default=0)),
                ('failed_tests_count', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=list, help_text='Array of {test_name, status, severity, recommendation}')),
            ],
            options={
                'db_table': 'security_scan_reports',
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(default='Recognized Device', max_length=255)),
                ('has_face_biometric', models.BooleanField(default=False, help_text='True if user enrolled face biometric on this device')),
                ('face_signature_hash', models.CharField(blank=True, help_text='Hash of the enrolled face template', max_length=255, null=True)),
                ('trust_status', models.CharField(choices=[('trusted', 'Trusted'), ('removed', 'Removed')], default='trusted', max_length=10)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_devices',
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_entered', models.CharField(blank=True, help_text='Email that was typed into the login form', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('face_biometric_verified', models.BooleanField(default=False, help_text='True if user passed face recognition during this login')),
                ('face_signature_hash', models.CharField(blank=True, help_text='Hash of the face scan data submitted with this login', max_length=255, null=True)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('risk_reasons', models.JSONField(blank=True, default=list, help_text='List of reasons that contributed to the risk score')),
                ('impossible_travel_detected', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text="NULL when the login email doesn't match any user", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_event_user_id_ab7d31_idx'), models.Index(fields=['ip_address', '-created_at'], name='login_event_ip_addr_e5e316_idx'), models.Index(fields=['risk_level', '-created_at'], name='login_event_risk_le_1f6fd6_idx')],
            },
        ),
    ]
