# Generated by Django 4.2.30 on 2026-07-16 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0002_webauthncredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('reg', 'Registration'), ('auth', 'Authentication')], max_length=10)),
                ('challenge', models.TextField(help_text='Base64url-encoded challenge bytes')),
                ('rp_id', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webauthn_challenges',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'purpose')},
            },
        ),
    ]
